version: 1.0.{build}
image: Visual Studio 2017
platform: x64
build_script:
- cmd: >-
    hg clone https://bitbucket.org/wowmodelviewer/wow-model-viewer-sdk -r f8f6691

    cd wow-model-viewer-sdk

    .\wmv_set_env.bat

    mkdir C:\projects\wowmodelviewer\build

    cd C:\projects\wowmodelviewer\build

    cmake -G "Visual Studio 15 2017 Win64" ..\src

    cmake --build . --target release --config Release
test: off
