version: 0.9.0.{build}
image: Visual Studio 2017

before_build:
- cmd: >-
    hg clone https://bitbucket.org/wowmodelviewer/wmv_sdk -r e96407a
    
    cd wmv_sdk

    .\wmv_set_env.bat

    mkdir C:\projects\wowmodelviewer\build

    cd C:\projects\wowmodelviewer\build

    cmake -G "Visual Studio 15 2017 " -DBUILDNUMBER=%APPVEYOR_BUILD_NUMBER% ..\src

build_script:
- cmd: >-
    cmake --build . --target release --config Release
    
    cd C:\projects\wowmodelviewer\bin

    ren WMV_Installer.exe WMV_Installer_v%APPVEYOR_BUILD_VERSION%.exe

test: off

for:
-
  branches:
    only:
      - default
  
  artifacts:
    - path: bin\WMV_Installer_v%APPVEYOR_BUILD_VERSION%.exe
