version: 0.9.0.{build}
image: Visual Studio 2013
build_script:
- cmd: >-
    hg clone https://bitbucket.org/jeromnimo/wmv_sdk -r 3911b29

    cd wmv_sdk

    .\wmv_set_env.bat

    mkdir C:\projects\wowmodelviewer\build

    cd C:\projects\wowmodelviewer\build

    cmake -G "Visual Studio 12 2013" -DBUILDNUMBER=%APPVEYOR_BUILD_NUMBER% ..\src

    cmake --build . --target release --config Release

	ren ..\bin\WMV_Installer.exe ..\bin\WMV_Installer_%version%.exe
test: off

artifacts:
  - path: bin\WMV_Installer_%version%.exe
